apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: akv-cluster-secret-read
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: aws-secret-manager-sa