{{- range $key, $value := .Values.platformApplications }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $value.appName }}-application
  namespace: {{ $value.argocdNamespace }}
  # finalizers:
  # - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ $value.applicationNamespace }}  
  project: {{ $value.applicationProject }}
  sources:
    - repoURL: {{ $value.repoUrl }}
      targetRevision: {{ $value.branch }}
      path: 02-apps/apps-in-app/platform/{{ $value.appName }}
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    {{ if $value.replace }}
    syncOptions:
      - Replace=true
      - CreateNamespace=true
    {{- end }}
    retry:
      limit: 20
---
{{- end }}
