apiVersion: v1
kind: Service
metadata:
  labels:
    app: pipeline-vote-api
  name: pipeline-vote-api
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
  selector:
    app: pipeline-vote-api
