{{ $argoNamespace := .Values.argoInstanceName }}
{{- range $key, $value := .Values.managedNamespaces }}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: {{ $argoNamespace }}-argo-rolebinding
  namespace: {{ $value.name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io  
  kind: Role
  name: {{ $argoNamespace }}-role
subjects:
- kind: ServiceAccount
  name: {{ $argoNamespace }}-argocd-argocd-application-controller
  namespace: {{ $argoNamespace }}
  
---
{{- end }}