
namespace:
  namespaceNames:
  - name: prod
  - name: dev

argoInstanceName: tenant-apps

managedNamespaces:
- name: openshift-operators
- name: openshift-gitops
- name: openshift-pipelines


global:
  openshiftGitopsNamespace: openshift-gitops
  clusterDomain: apps.dd-aro.eastus.aroapp.io

