apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalsecrets.pipelinesecretname }}
  namespace: {{ .Values.externalsecrets.pipelinesnamespace }}
spec:
  refreshInterval: 10m
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.externalsecrets.clustersecretstorename }}
  target:
    name: {{ .Values.externalsecrets.pipelinesecretname }}
  data:
  - secretKey: config.json
    remoteRef:
      key: secret/registryCred