apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalsecrets.webhookexternalsecretname }}-external-secret
  namespace: {{ .Values.externalsecrets.pipelinesnamespace }}
spec:
  refreshInterval: 10m
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.externalsecrets.clustersecretstorename }}
  target:
    name: {{ .Values.externalsecrets.webhooktargetsecret }}
  data:
  - secretKey: webhookSecret
    remoteRef:
      key: secret/webhookSecret