apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/managed-by: EventListener
    app.kubernetes.io/part-of: Triggers
    argocd.argoproj.io/instance: pipelines-config
    eventlistener: {{ .Values.event_listener_name }}
  name: el-{{ .Values.event_listener_name }}
spec:
  port:
    targetPort: http-listener
  to:
    kind: Service
    name: el-{{ .Values.event_listener_name }}
    weight: 100