{{- range $key, $value := .Values.groups }}
apiVersion: user.openshift.io/v1
kind: Group
metadata:
  name: {{ $value.name }}
  namespace: openshift-gitops
users:
{{- range $v, $k := $value.users }}
- {{ $k }}
{{- end }}
---
{{- end }}