
global:
  openshiftGitopsNamespace: openshift-gitops
  clusterDomain: apps.dd-aro.eastus.aroapp.io

projects:
  - name: devops
    namespace: openshift-gitops
    sourcerepos:
    - https://github.com/rh-fran6/gitops.git
  - name: platform-config
    namespace: openshift-gitops
    sourcerepos:
    - https://github.com/rh-fran6/gitops.git
  - name: rbac
    namespace: openshift-gitops
    sourcerepos:
    - https://github.com/rh-fran6/gitops.git
  - name: miscellaneous
    namespace: openshift-gitops
    sourcerepos:
    - https://github.com/rh-fran6/gitops.git
  - name: security
    namespace: openshift-gitops
    sourcerepos:
    - https://github.com/rh-fran6/gitops.git
  - name: tenant-a
    namespace: tenant-argo-ns
    sourcerepos:
    - https://github.com/rh-fran6/gitops.git
  - name: tenant-b
    namespace: tenant-argo-ns
    sourcerepos:
    - https://github.com/rh-fran6/gitops.git
  - name: tenant-c
    namespace: tenant-argo-ns
    sourcerepos:
    - https://github.com/rh-fran6/gitops.git
  - name: shared-services
    namespace: tenant-argo-ns
    sourcerepos:
    - https://github.com/rh-fran6/gitops.git

argocd:
  - name: tenant
    namespace: tenant-argo-ns

platformApplications:
  ##  Applications in platform-admin namespace
  - appName: openshift-pipelines
    repoUrl: https://github.com/rh-fran6/gitops.git
    branch: main
    argocdNamespace: openshift-gitops
    applicationProject: devops
    applicationNamespace: openshift-pipelines
    replace: false

  - appName: external-secrets
    repoUrl: https://github.com/rh-fran6/gitops.git
    branch: main
    argocdNamespace: openshift-gitops
    applicationProject: security
    applicationNamespace: external-secrets-operator
    replace: false

  - appName: argocd-image-updater
    repoUrl: https://github.com/rh-fran6/gitops.git
    branch: main
    argocdNamespace: openshift-gitops
    applicationProject: devops
    applicationNamespace: openshift-gitops
    replace: false
  
  - appName: kyverno
    repoUrl: https://github.com/rh-fran6/gitops.git
    branch: main
    argocdNamespace: openshift-gitops
    applicationProject: security
    applicationNamespace: openshift-gitops
    replace: true

tenantApplications:
  - appName: demo-pipeline-app-frontend
    repoUrl: https://github.com/rh-fran6/gitops.git
    branch: main
    argocdNamespace: tenant-argo-ns
    applicationProject: tenant-a
    applicationNamespace: tenant-app-1
    path: tenants/frontend-deploy

  - appName: demo-pipeline-app-backend
    repoUrl: https://github.com/rh-fran6/gitops.git
    branch: main
    argocdNamespace: tenant-argo-ns
    applicationProject: tenant-a
    applicationNamespace: tenant-app-1
    path: tenants/backend-deploy

  - appName: demo-hello-app
    repoUrl: https://github.com/rh-fran6/gitops.git
    branch: main
    argocdNamespace: tenant-argo-ns
    applicationProject: tenant-a
    applicationNamespace: tenant-app-2
    path: tenants/hello-world

sharedApplications:
  - appName: shared-services
    repoUrl: https://github.com/rh-fran6/gitops.git
    branch: main
    argocdNamespace: tenant-argo-ns
    applicationProject: shared-services
    applicationNamespace: shared
    path: shared/postgresql






