## Read SP app ##
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.externalsecrets.esosecretname }}
type: Opaque
data:
  ClientID: {{ .Values.rbac_roles.read_client_id }}  
  ClientSecret: {{ .Values.rbac_roles.read_client_secret }} 

