apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql-db-1
  namespace: postgresql
spec:
  serviceName: postgresql-db-service
  selector:
    matchLabels:
      app: postgresql-db
  replicas: 1
  template:
    metadata:
      labels:
        app: postgresql-db
    spec:
      containers:
        - name: postgresql-db
          image: postgres:latest
          volumeMounts:
            - mountPath: /data
              name: cache-volume
          env:
            - name: PGDATA
              value: /data/pgdata

            - name: POSTGRES_DB
              value: keycloak

            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret-from-akv
                  key: psqluser

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret-from-akv
                  key: psqlpw
      volumes:
        - name: cache-volume
          emptyDir: {}