## ArgoCD Parameters ##
argocdInstances:
  - name: tenant-apps
    defaultRbacPolicy: role:none
    rbacScopes: "'[groups]'"
    projects:
    - name: prod
      argocd: tenant-apps
      sourceRepos: 
      - git@github.com:rh-fran6/argocd-gitops.git
    - name: dev
      argocd: tenant-apps
      sourceRepos: 
      - "'*'"

applications:
  ##  Applications in application namespace
  - appName: pipeline-prod-frontend
    repoUrl: https://github.com/rh-fran6/gitops.git
    imageName: quay.io/fanyaegb/pipeline-vote-ui:prod
    branch: main
    argocdNamespace: tenant-apps
    applicationProject: prod
    applicationNamespace: pipeline-prod-frontend

  - appName: pipeline-prod-backend 
    remoteAppNamespace: tenant-apps
    imageName: quay.io/fanyaegb/pipeline-vote-api:prod
    repoUrl: https://github.com/rh-fran6/gitops.git
    branch: main
    argocdNamespace: tenant-apps
    applicationProject: prod
    applicationNamespace: pipeline-prod-backend

  - appName: argocdimageupdater
    repoUrl: https://github.com/rh-fran6/gitops.git
    branch: main
    argocdNamespace: tenant-apps
    applicationProject: prod
    applicationNamespace: tenant-apps

global:
  openshiftGitopsNamespace: openshift-gitops
  clusterDomain: apps.dd-aro.eastus.aroapp.io

